### ISSUE TITLE
Prevent scroll to ID.

### ISSUE THREAD

**Issue by Dthalion** [timabell/jquery.stickytabs#1] opened 2015-02-19 17:14 UTC
In my current build of a Bootstrap site, using Bootstrap Tabs, when I click on a Tab in the navigation pane, the page jumps down to the Tab content, and hides the navigation pane above, which means the user has to scroll back up just to select another tab.  How can I disable the jump/scroll to ID?  Or what do I add to the code to scrollTop automatically.  I have tried, preventDefault, scrollTOP(0,0) etc.  but I can't get it to stop.

Any help would be greatly appreciated especially because my last resort right now is to stop using the plugin.

**Comment by timabell** [comment] 2015-02-19 17:25
Hmm, that's a tricky one, because the reason it's scrolling is because the browser is detecting the #anchor on the end of the url when you load the page. I don't know if there's any way you could intercept this. It's not really the plugin's doing, more an unfortunate side-effect of using the # to represent a tab.

In terms of graceful degradation you could argue it's correct behaviour as without any css/js the tabs would be listed as divs vertically (depending on markup), so this would scroll to the right div. This indicates to me that a fixup in javascript might be appropriate, but I'm also not sure how you go about it.

If you have any bright ideas I'm open to pull requests.

Cheers for the feedback.

**Comment by curtisweeks** [comment] 2015-03-09 22:40
Adding `window.scrollTo(0, 0);` at the end of the `showTabFromHash` function seems to work.

**Comment by timabell** [comment] 2015-03-10 09:50
@jabbtech So that would always scroll back up to the top of the page. I don't think that would suit all use-cases of this plugin so you'd have to figure out some way to make that optional or think of a different approach.

When you say the end of `showTabFromHash()`, do you mean after it in the stickytabs code, or actually inside it (i.e. external to this project)?

refs
- w3 draft spec of scrollTo http://dev.w3.org/csswg/cssom-view/#extensions-to-the-window-interface
- http://stackoverflow.com/questions/1925671/javascript-window-scroll-vs-window-scrollto

**Comment by timabell** [comment] 2015-03-10 09:55
One option would to be to make the anchor name of the tab not match the one in the url, say with a prefix or suffix that could be programmatically stripped off before comparing. That way the browser would have nothing to scroll to. I'm not sure how keen I am on this as it breaks the graceful degradation, but it's probably better on balance.

**Comment by timabell** [comment] 2015-03-10 10:11
You might want to see if the updated code in https://github.com/aidanlister/jquery-stickytabs has a solution

**Comment by curtisweeks** [comment] 2015-03-10 13:53
@timabell I agree. The one-liner is not really sufficient for this plugin. An optional way to invoke the stickytabs could involve checking for an HTML5 data-attribute. Something along the lines of:

**Jquery**
`$(a).click(function () { if ($(this).data('stickylink') === 'true') { ... } }`

**HTML**
`<a href="foo.html#tab" data-stickylink="true">foo</a>`

I'm working on a fork but it covers too many changes at once. I'll work on providing something specific to this request and then break down the other changes into separate issues.

**Comment by timabell** [comment] 2015-03-10 14:07
Sounds like a possible solution. By the way, you might want to keep an eye on https://github.com/aidanlister/jquery-stickytabs/issues/2 in the other repo as I'm currently trying to resolve the divergence of the forks, so it's likely that my repo might cease to exist in its current form.

**Comment by curtisweeks** [comment] 2015-03-10 16:14
OK. Sounds good. For now I'm using something like:

`if ($('body').hasClass('stickyTabsTop')) { window.scrollTo(0, 0); }`

Inside `showTabFromHash()`. I'll see if this is a good fit for (or even needed in) the other repo.

Thanks!

**Comment by aidanlister** [comment] 2015-03-13 09:35
I believe the issue is resolved in https://github.com/aidanlister/jquery-stickytabs

**Comment by timabell** [comment] 2015-03-13 19:58
I'm now tracking and packaging upstream. NuGet package of v1.2.0 released.
- If there's any problems with the js code please report them in aidan's repo
- If there's any problems with the packaging or you need a new release from upstream please open an issue in this issue tracker.

Thanks

**Closed as completed by timabell** 2015-03-13 19:58 UTC
